### ISSUE TITLE
UCXVan A100 multi-GPU support 

### ISSUE THREAD

**Issue by eric-haibin-lin** [bytedance/ps-lite#45]
# Background
## Capability of UCX
- With the current version of openucx, a UCX context cannot choose the optimal route for multiple GPUs. However, if a UCX context and the data is bound to a particular GPU, then the data will be sent/recv with the optimal route. 
- Memory pinning: Each time a memory is pinned / unpinned for GPUDirect RDMA, there's some overhead. Ideally we want to avoid changing the memory buffer address when sending/receiving GPU data with GDR. 
## Use cases
Testing code https://github.com/bytedance/ps-lite/pull/46
- 1 PSWorker per node. The PSWorker handles the data from all 8 GPUs & GPU on that node on the same process
- Multiple PSWorkers per node. There are multiple processes, and each process has a PSWorker that handles the data of a particular GPU (and the CPU).

# Proposed APIs
## Ps-lite user experience 
```
// assume we have done cudaMalloc with `data` (char*) on GPU 0 previous.
DeviceType curr_device_type = ps::kGPU;
int curr_device_id = 0;
// specify the target device
DeviceType tgt_device_type = ps::kGPU;
int tgt_device_id = 2;
SArray<char> vals(data, len, false,
                  curr_device_type, curr_device_id,
                  tgt_device_type, tgt_device_id);

PSKV pskv;
pskv.keys.push_back(0);
pskv.lens.push_back(1024000);
pskv.size = 1024000;
kv_worker->ZPush(pskv.keys, vals, pskv.lens);
```

```
void RequestHandler(const KVMeta& req_meta, const KVPairs<Val>& req_data, KVServer<Val>* server) {
  if (req_meta.dst_device_type == kGPU) {
    // do something with the received GPU data
  } else {
    // do something with the received CPU data
  }
};
```

## Ps-lite data structures changes
Message.meta stores the device information 
```
enum {
  kCPU,
  kGPU
} DeviceType;

struct Meta {
 DeviceType src_dev_type;
 uint8_t src_dev_id;
 DeviceType dst_dev_type;
 uint8_t dst_dev_id;
 ...
}

// now each ucp_context is bound to a port for a ucp_listener and a ucp_worker
// we replace the monolithic `int port` with an array of ports and devices
struct Node {
  uint8_t num_ports;
  int ports[32];
  DeviceType device_types[32];
  uint8_t device_ids[32];
}
```
Device extension for SArray
```
template<typename V>
class SArray {
 public:
  // Zero-copy constructor for device data
  SArray(V* data, size_t size, bool deletable = false,
         DeviceType curr_device_type, int curr_device_id,
         DeviceType tgt_device_type, int tgt_device_id);

  // copy-assignment operator
  template <typename W> void operator=(const SArray<W>& arr);

 private:
   DeviceType curr_device_type_;
   int curr_device_id_;
   DeviceType tgt_device_type_;
   int tgt_device_id_;
};
```
KVServer buffer registration
```
// to send data from local GPU to a remote GPU, we need the remote GPU
// to designate a memory buffer that can hold the result, so that we avoid
// a memory copy.
KVServer {
  public: 
    RegisterRecvBuffer(SArray<Key>& keys, const SArray<Val>& vals,
                       const SArray<int>& lens = {}, int cmd = 0);
};
```
UCXVan
```
public: 
  // creates multiple ucp_listeners and ports based on `CUDA_VISIBLE_DEVICES`
  // Update `my_node.ports` directly inside `Bind`
  // the return type is changed from int to void
  void Bind(const Node &my_node, int max_retry);

  // Connect to the target node based on the ports information
  // stored inside `node`.
  void Connect(const Node &node);

  // picks the corresponding ucp_context based on src_device_id
  // and dst_device_id
  int SendMsg(Message& msg);

  // set the curr_device_id upon receiving the message. 
  int RecvMsg(Message& msg);

  // register the receiving buffer for provided keys
  void RegisterRecvBuffer(SArray<Key>& keys, const SArray<Val>& vals,
                          const SArray<int>& lens = {}, int cmd = 0);

private:
  // multiple ucx contexts
  // also need to store the mapping for context <-> dev_type / dev_id
  std::vector<ucp_context_h> contexts_;
 ```

## BytePS changes 
This part should be handled by the BytePS dev team. 
### Memory management 
As using GDR with frequently changing GPU data address could lead to pinning/unpinning overheads, using the same GPU buffer is preferred. There are two options:
1. BytePS manages the buffers registered for communication. Upon each push, we copy the original tensor to the communication buffer before sending it out. Similarly, we use the communication buffer to hold the result of pull, and then copy the data to the destination tensor. 
2. BytePS directly passes whatever GPU memory that needs to be sent/received, and relies on UCX's lazy pinning optimizations to mitigate the overhead. 
The option mainly affects BytePS's memory management implementation. From UCXVan's point of view, it always tries to pin the GPU data passed to it. 
### PushPull and key encoding on A100 
On A100 nodes, each PCI-e switch is connected with 2 GPUs and an NIC. A pushpull call in BytePS would become the following series of operations on the local node:
- reduce scatter, which results in 8 GPU tensors
- ZPush/ZPull with the (same) key and corresponding device IDs
- All-gather. 

Note that the above ps-lite change does not affect how ps-lite scheduler assign ranks to each node. BytePS partitions a tensor as usual (1 ps key for every 4MB data chunk). The key encoding logic also stays the same, where the first x bits are reserved for the target node id. When sending a key with data residing on different GPUs, we just need to annotate the source SArray with the corresponding device id.

**Comment by bobzhuyb** [comment]
@brminich, please review and add relevant people to this thread

**Comment by brminich** [comment]
@yosefe, @bureddy, @Akshay-Venkatesh

**Comment by brminich** [comment]
@eric-haibin-lin, @bobzhuyb, we will discuss it internally and will get back in a day or two

**Comment by brminich** [comment]
@dmitrygx

**Comment by brminich** [comment]
@eric-haibin-lin, the proposed changes seem to be sufficient for UCX van.
Can you please check whether my understanding of the proposed API is correct?

**Scheduler:**
	- Does not work with GPUs, one UCX context is enough, also just one connection per every worker and server is needed

**Worker:**
	- Needs to create a single UCX context, because uses only one local GPU (set `my_node->num_ports = 1` in `van->Bind()`)
	- Need to connect to many server UCX contexts(i. e. create `Node->num_ports` endpoints in the `van->Connect()` call)
	- Can ignore `Meta->src_dev_id` and `Meta->src_dev_type` when sending a message (PUSH request)
	- Uses `Meta->dst_dev_id` and `Meta->dst_dev_type` to find on which ep to send a message to the server

**Server:**
	- Uses all local GPUs
	- Use one remote GPU per worker
	- Need to create `myNode->num_ports` UCX contexts
	- Every server UCX context needs to connect with one remote context of each worker (in the `van->connect()` call) 
	- Uses `Meta->src_dev_id` and `Meta->src_dev_type` to find a proper local UCX context and its ep when sending a message (PULL response)
	- Can ignore `Meta->dst_dev_id` and `Meta->dst_dev_type` when sending a message (PULL response), because every server context connects to just one remote worker UCX context
        - For storing push requests data need to use memory provided in` RegisterRecvBuffer()`
	
**Questions:**
	- What does cmd parameter represent in `RegisterRecvBuffer()`?
	- Why is it needed to set `curr_device_id` in `RecvMsg()` if the message itself is most probably already received by the UCX VAN?

**Comment by eric-haibin-lin** [comment]
> Scheduler:
> - Does not work with GPUs, one UCX context is enough, also just one connection per every worker and server is needed

That's correct. 

> Worker:
> - Needs to create a single UCX context, because uses only one local GPU (set my_node->num_ports = 1 in van->Bind())

That's only sufficient for use case 2. In our production system, we have both use case 1 & 2:

1. 1 PSWorker/PSServer per node. The PSWorker/PSServer communicates the data from all 8 GPUs & GPU on that node on the same process. 
2. 1 PSWorker/PSServer per GPU, (i.e. multiple PSWorkers/PSServer per node). There are multiple processes, and each process has a PSWorker/PSServer that only handles the data of a particular GPU (and the CPU).

In use case 1, there is only one PSWorker handling all GPUs on the same node. We definitely need to have multiple UCX contexts on the same PSWorker. 

> - Need to connect to many server UCX contexts(i. e. create Node->num_ports endpoints in the van->Connect() call)

Yes 

> - Can ignore Meta->src_dev_id and Meta->src_dev_type when sending a message (PUSH request)

As mentioned above, a worker could be sending data from multiple GPUs. That is why we encode `src_dev_id` in the SArray, such that the Van knows which GPU device the data reside.

> - Uses Meta->dst_dev_id and Meta->dst_dev_type to find on which ep to send a message to the server

Yes


> Server:
> - Uses all local GPUs
> - Use one remote GPU per worker
> - Need to create myNode->num_ports UCX contexts
> - Every server UCX context needs to connect with one remote context of each worker (in the van->connect() call)
> - Uses Meta->src_dev_id and Meta->src_dev_type to find a proper local UCX context and its ep when sending a message (PULL response)
> - Can ignore Meta->dst_dev_id and Meta->dst_dev_type when sending a message (PULL response), because every server context connects to just one remote worker UCX context
> - For storing push requests data need to use memory provided in RegisterRecvBuffer()

As mentioned above, both the server and worker may use one or multiple GPUs. Every server UCX context needs to connect with ALL remote contexts of each worker. Therefore, the server have to use `dst_dev_id` to find which remote worker UCX context to send data. 


> Questions:
> - What does cmd parameter represent in RegisterRecvBuffer()?

I left the interface consistent with `ZPush` and it's currently not used. For now, it's safe to just ignore it. 

> - Why is it needed to set curr_device_id in RecvMsg() if the message itself is most probably already received by the UCX VAN?

You're right. Setting either curr_device_id or dst_device_id in the received message SArray is fine.

**Comment by brminich** [comment]
So, there is no much difference in server/worker flows then. Both of them have to create N^2 connections (where N is num of GPUs) connecting all local gpus with all remote GPUs

Is this a final API? Can we start prototyping based on it?

**Comment by eric-haibin-lin** [comment]
@brminich yes, let's proceed with this API :)

**Comment by brminich** [comment]
@eric-haibin-lin, ok, I'll change UCX van according to the proposed API. Do you have this API implemented on some private branch or it is work in progress?

**Comment by eric-haibin-lin** [comment]
> @eric-haibin-lin, ok, I'll change UCX van according to the proposed API. Do you have this API implemented on some private branch or it is work in progress? 

It's not yet implemented. I'll try to create a branch with the updated SArray api in a few days

**Comment by eric-haibin-lin** [comment]
Just to double check how we split the work:
- Bytedance (@eric-haibin-lin) will update `struct Meta`, `struct Node`, `class SArray`, `KVServer::RegisterRecvBuffer`
- NV (@brminich ) will implement the functionalities inside `class UCXVan` 

@brminich does that sound good?

**Comment by brminich** [comment]
@eric-haibin-lin, yes.
BTW, do you see any problems with using CUDA API in UCX Van (cudaSetDevice)? I'd like to set a device before calling UCX context creation routine, so it can select optimal HCA different GPUs/contexts

**Comment by eric-haibin-lin** [comment]
> @eric-haibin-lin, yes.
> BTW, do you see any problems with using CUDA API in UCX Van (cudaSetDevice)? I'd like to set a device before calling UCX context creation routine, so it can select optimal HCA different GPUs/contexts

Will `cudaSetDevice` be called also at every send/recv, or only during creation? I don't see a problem if it's called only at creation.

**Comment by brminich** [comment]
> > @eric-haibin-lin, yes.
> > BTW, do you see any problems with using CUDA API in UCX Van (cudaSetDevice)? I'd like to set a device before calling UCX context creation routine, so it can select optimal HCA different GPUs/contexts
> 
> Will `cudaSetDevice` be called also at every send/recv, or only during creation? I don't see a problem if it's called only at creation.

only before context creation

**Comment by jdaaph** [comment]
@brminich Hello, when I'm testing the ps-lite test_benchmark with UCX van I get the following error messages (but the program can continue to run): `[14:56:06] src/./ucx_van.h:213: failed to close ep: 0x7f7a806be140` Is that something we need to fix when we compile? This error seems to only occur on some of our machines and when we link UCX to internal managed versions of rdmacm / ibverbs. Thanks!

**Comment by brminich** [comment]
> @brminich Hello, when I'm testing the ps-lite test_benchmark with UCX van I get the following error messages (but the program can continue to run): `[14:56:06] src/./ucx_van.h:213: failed to close ep: 0x7f7a806be140` Is that something we need to fix when we compile? This error seems to only occur on some of our machines and when we link UCX to internal managed versions of rdmacm / ibverbs. Thanks!

#51 should fix the issue

**Comment by brminich** [comment]
@eric-haibin-lin, I have a question about new RegisterRecvBuffer() func. On the server we have to use different receive buffer for every pair of sender(worker) and key. How should/can it be achieved with this func?

**Comment by brminich** [comment]
@eric-haibin-lin, can you please clarify?

**Comment by eric-haibin-lin** [comment]
Hi @brminich  really sorry for the late reply. 

This is a good point - yes, we need to register the buffer for every worker - key pair. Shall we add the sender to the RegisterRecvBuffer API of KVServer and Van:
```
    KVServer::RegisterRecvBuffer(int worker_id, // the sender
        SArray<Key>& keys, 
        const SArray<Val>& vals, // contains src_device and tgt_device info
        const SArray<int>& lens = {}, int cmd = 0);
   
   Van::RegisterRecvBuffer(Message msg);
```
And SArray contains the info of src and destination device of each message send/recv:
```
template<typename V>
class SArray {
 public:
   DeviceType src_device_type_; // was: curr_device_type
   int src_device_id_; // was: curr_device_id
   DeviceType tgt_device_type_; 
   int tgt_device_id_;
};


```
What do you think?

**Comment by brminich** [comment]
Let me clarify:
1. UCX van will have to implement `RegisterRecvBuffer(Message msg)`
2. `msg.meta` will contain 2 fields sufficient for proper recv buffer caching:
-  sender (identifies particular worker)
-  key
3. Van does not really need to parse `msg.data` (`src_device_id` and `type`) for receive buffers registration 

Another comment is https://github.com/bytedance/ps-lite/pull/46#discussion_r536446616. Does it mean that worker will also register recv buffer for the data it is going to pull?

**Comment by eric-haibin-lin** [comment]
Thanks for the clarification!

> 1. Van does not really need to parse `msg.data` (`src_device_id` and `type`) for receive buffers registration

I was assuming that the user allocates some GPU buffer and pass that as msg.data[1] for registration. 

> Does it mean that worker will also register recv buffer for the data it is going to pull?

Currently the ZPull API always takes a `val` SArray, which can already be used as the recv buffer.

**Comment by brminich** [comment]
> Thanks for the clarification!
> 
> > 1. Van does not really need to parse `msg.data` (`src_device_id` and `type`) for receive buffers registration
> 
> I was assuming that the user allocates some GPU buffer and pass that as msg.data[1] for registration.

Ok, can I rely on `sender` and `key` from `msg.meta` (to identify what buffer belongs to what push)?

> 
> > Does it mean that worker will also register recv buffer for the data it is going to pull?
> 
> Currently the ZPull API always takes a `val` SArray, which can already be used as the recv buffer.

Ok, can we always use it instead of the caching buffer used for push?

**Comment by brminich** [comment]
@eric-haibin-lin, what would be device ids for CPU type of device? Can I assume it is always be zero?

**Comment by eric-haibin-lin** [comment]
> > Thanks for the clarification!
> 
> > 
> 
> > > 1. Van does not really need to parse `msg.data` (`src_device_id` and `type`) for receive buffers registration
> 
> > 
> 
> > I was assuming that the user allocates some GPU buffer and pass that as msg.data[1] for registration.
> 
> 
> 
> Ok, can I rely on `sender` and `key` from `msg.meta` (to identify what buffer belongs to what push)?
> 
> 

Yes

> 
> > 
> 
> > > Does it mean that worker will also register recv buffer for the data it is going to pull?
> 
> > 
> 
> > Currently the ZPull API always takes a `val` SArray, which can already be used as the recv buffer.
> 
> 
> 
> Ok, can we always use it instead of the caching buffer used for push?
> 
> 
> 
> 
> 
> 
Yes. As a side note, currently BytePS uses the same buffer for both push and pull. But for ps-lite it's better to use the one provided in zpull.

**Comment by eric-haibin-lin** [comment]
> @eric-haibin-lin, what would be device ids for CPU type of device? Can I assume it is always be zero? 

Good question. We may have 1 id for each numa node,  if we want to use ps-lite in high performance cpu only mode. @jdaaph what do you think?
