### ISSUE TITLE
ucx van with GDR

### ISSUE THREAD

**Issue by pleasantrabbit** [bytedance/ps-lite#54]
If I want to register a GPU buffer, then use that buffer with `ucp_tag_send_nb()`, what are the steps to do that? Is there code samples I can use as a reference?

These are [some memory registration related settings](https://github.com/openucx/ucx/blob/1aa7505db782bea95aa004853575919ff35a6bfd/src/uct/ib/base/ib_md.c#L61) in ucx: 
```
    {"REG_METHODS", "rcache,odp,direct",
     "List of registration methods in order of preference. Supported methods are:\n"
     "  odp         - implicit on-demand paging\n"
     "  rcache      - userspace registration cache\n"
     "  direct      - direct registration\n",
     ucs_offsetof(uct_ib_md_config_t, reg_methods), UCS_CONFIG_TYPE_STRING_ARRAY},
```
is `export UCX_IB_REG_METHODS=rcache` what I need to manually register memory regions?

**Comment by pleasantrabbit** [comment]
@brminich

**Comment by brminich** [comment]
why do you want to register it manually? UCX does it implicitly

**Comment by pleasantrabbit** [comment]
> why do you want to register it manually? UCX does it implicitly

@brminich registering GPU memory manually should improve performance.  If we push a different memory chunk every time, UCX would register it before sending it out. It would be too expensive to register memory for every push.

**Comment by brminich** [comment]
You can use `ucp_mem_map` to register memory in advance, but you have to provide UCX context in it somehow(which is created in UCXVan->Start()).

**Comment by brminich** [comment]
@pleasantrabbit, maybe we can define `Register` function in Van class, so you could call it in PS-lite  and UCX Van will register memory on the proper context

**Comment by pleasantrabbit** [comment]
> @pleasantrabbit, maybe we can define `Register` function in Van class, so you could call it in PS-lite and UCX Van will register memory on the proper context

@brminich if I register a pointer `ptr` with `length = 4096`, then pass `ptr + 8` to `ucp_tag_send_nb()`, will UCX recognize that `ptr + 8` is already registered and skip the registration step inside UCX?
e.g.
```
ucp_mem_map(addr = ptr, length = 4096);
ucp_tag_send_nb(ptr + 8, length = 16);
```

**Comment by eric-haibin-lin** [comment]
Hi @brminich does GDR support registering a mem address opened by Cuda IPC?

**Comment by brminich** [comment]
> > @pleasantrabbit, maybe we can define `Register` function in Van class, so you could call it in PS-lite and UCX Van will register memory on the proper context
> 
> @brminich if I register a pointer `ptr` with `length = 4096`, then pass `ptr + 8` to `ucp_tag_send_nb()`, will UCX recognize that `ptr + 8` is already registered and skip the registration step inside UCX?
> e.g.
> 
> ```
> ucp_mem_map(addr = ptr, length = 4096);
> ucp_tag_send_nb(ptr + 8, length = 16);
> ```

@pleasantrabbit, yes, UCX will recognize

**Comment by brminich** [comment]
> Hi @brminich does GDR support registering a mem address opened by Cuda IPC?

@eric-haibin-lin, do you mean `cudaIpcGetMemHandle`? 
@Akshay-Venkatesh

**Comment by Akshay-Venkatesh** [comment]
> > Hi @brminich does GDR support registering a mem address opened by Cuda IPC?
> 
> @eric-haibin-lin, do you mean `cudaIpcGetMemHandle`?
> @Akshay-Venkatesh

This is unsupported. GDR/Gdrcopy registration is supported on pinned memory (cudaMalloc/cuMemAlloc).

**Comment by eric-haibin-lin** [comment]
> > > Hi @brminich does GDR support registering a mem address opened by Cuda IPC?
> 
> > 
> 
> > @eric-haibin-lin, do you mean `cudaIpcGetMemHandle`?
> 
> > @Akshay-Venkatesh
> 
> 
> 
> This is unsupported. GDR/Gdrcopy registration is supported on pinned memory (cudaMalloc/cuMemAlloc).

Yes, I meant cudaIpcGetMemHandle. Thanks for the confirmation @Akshay-Venkatesh @brminich :)

**Comment by pleasantrabbit** [comment]
> > > Hi @brminich does GDR support registering a mem address opened by Cuda IPC?
> > 
> > 
> > @eric-haibin-lin, do you mean `cudaIpcGetMemHandle`?
> > @Akshay-Venkatesh
> 
> This is unsupported. GDR/Gdrcopy registration is supported on pinned memory (cudaMalloc/cuMemAlloc).

@Akshay-Venkatesh @brminich Do you mean GDR only works with memory directly obtained by calling `cudaMalloc()`? 

Consider this scenario: proc A calls `cudaMalloc()` to get a GPU pointer `devPtrA`, then calls `cudaIpcGetMemHandle()` to get a `cudaIpcMemHandle_t`, passes this handle to proc B. proc B calls `cudaIpcOpenMemHandle()` to obtain `devPtrB`, now if we pass `devPtrB` to `ucp_tag_send_nb()` directly (or call `ucp_mem_map(devPtrB)` then pass `devPtrB` to `ucp_tag_send_nb()`), will GDR work? It seems like from proc B's point of view, `devPtrB` is just a normal GPU pointer.

**Comment by Akshay-Venkatesh** [comment]
> > > > Hi @brminich does GDR support registering a mem address opened by Cuda IPC?
> > > 
> > > 
> > > @eric-haibin-lin, do you mean `cudaIpcGetMemHandle`?
> > > @Akshay-Venkatesh
> > 
> > 
> > This is unsupported. GDR/Gdrcopy registration is supported on pinned memory (cudaMalloc/cuMemAlloc).
> 
> @Akshay-Venkatesh @brminich Do you mean GDR only works with memory directly obtained by calling `cudaMalloc()`?

That's correct.

> 
> Consider this scenario: proc A calls `cudaMalloc()` to get a GPU pointer `devPtrA`, then calls `cudaIpcGetMemHandle()` to get a `cudaIpcMemHandle_t`, passes this handle to proc B. proc B calls `cudaIpcOpenMemHandle()` to obtain `devPtrB`, now if we pass `devPtrB` to `ucp_tag_send_nb()` directly (or call `ucp_mem_map(devPtrB)` then pass `devPtrB` to `ucp_tag_send_nb()`), will GDR work? It seems like from proc B's point of view, `devPtrB` is just a normal GPU pointer.

This isn't supported.

**Comment by eric-haibin-lin** [comment]
Thanks @Akshay-Venkatesh for the reply. 

I am getting another error when using UCXVan. On start it reports:
```
terminate called after throwing an instance of 'dmlc::Error'
  what():  [05:29:53] ps-lite/src/./ucx_van.h:373: Check failed: (status) == UCS_OK ucp_init failed: Unsupported operation
```
Any idea why this happens?

`ucx_info -b` shows the following:
```
#define UCX_CONFIGURE_FLAGS       "--disable-logging --disable-debug --disable-assertions --disable-params-check --enable-mt --with-cuda=/opt/tiger/cuda_10_0 --prefix=/home/haibin.lin/docker/ucx_build --with-rdmacm=/home/haibin.lin/blade_byteps/cpp3rdlib/rdma-core --with-cuda=/opt/tiger/cuda_10_0"
#define UCX_MODULE_SUBDIR         "ucx"
#define VERSION                   "1.10"
#define restrict                  __restrict
#define test_MODULES              ":module"
#define ucg_MODULES               ":builtin"
#define ucm_MODULES               ":cuda"
#define uct_MODULES               ":cuda:ib:rdmacm:cma"
```

Thanks @Akshay-Venkatesh @brminich

**Comment by eric-haibin-lin** [comment]
The `Unsupported operation` error was resolved. There was an issue using our internal build system for ucx.

**Comment by eric-haibin-lin** [comment]
Hi @Akshay-Venkatesh @brminich 
my machine has 4 mlnx NICs, each with 200Gb/s bandwidth. When running ` test_benchmark` using CPU data with ucx van, with multi-rails = 4, I see that only 2 NICs are used, with throughput ~280Gb/s. Is there a way to use more than 4 rails to achieve higher throughput? 
On the other hand, with multi-rails=1, I see only 70 Gb/s. It seems kind of low. Is this expected?

**Comment by brminich** [comment]
@eric-haibin-lin, please set `UCX_MAX_RNDV_RAILS` to 4 to use 4 NICs.
